### ISSUE TITLE
Final CapStone Project - Kanban Board Setup

### ISSUE THREAD

**Issue by clintonjosephs** [clintonjosephs/book-a-doctor-backend#15]
Hello 😊,

Here is our kanban board set up for the final capstone group project. We choose a doctor themed application, see other details:

- Team Number: 5
    - Team member 1: @clintonjosephs 
    - Team member 2: @jaflih  
    - Team member 3: @Nuri1977 
    - Team member 4: @Mithi-code 
    - Team member 5: @AtillaTahak 

- Kanban Board: www.github.com/clintonjosephs/book-a-doctor-backend/projects/1
<img width="1508" alt="Screenshot 2022-05-31 at 14 31 27" src="https://user-images.githubusercontent.com/82473943/173866461-4a2d3649-c426-4a1c-9936-8c37efc3d6a6.png">

![IMG_20220615_174525](https://user-images.githubusercontent.com/61827773/173835333-514c8997-ade0-4b38-b804-39c4d8148ae3.png)
![IMG_20220615_174525 (copy)](https://user-images.githubusercontent.com/61827773/173835336-31141a14-e775-4cfa-939d-c91c89141848.png)
![IMG_20220615_174549](https://user-images.githubusercontent.com/61827773/173835338-6c83e9ca-fb33-4451-8881-411f602e6ec3.png)
![IMG_20220615_174613](https://user-images.githubusercontent.com/61827773/173835340-82b4ad77-2ddc-47be-a7ef-8cbb858a05ba.png)

**Comment by MuriloRoque** [comment]
Hi @clintonjosephs, @jaflih, @AtillaTahak, @Nuri1977, @Mithi-code,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
